/**
 * SHUNRECIPE — データベース
 * 旬野菜・レシピ・地域情報
 */

const APP_DATA = {
  // ─── 地域データ ───
  regions: [
    { id: "hokkaido", name: "北海道", postalPrefix: ["0"] },
    { id: "tohoku", name: "東北", postalPrefix: ["0"] },
    { id: "kanto", name: "関東", postalPrefix: ["1","2","3"] },
    { id: "chubu", name: "中部", postalPrefix: ["4","5"] },
    { id: "kinki", name: "近畿", postalPrefix: ["5","6"] },
    { id: "chugoku", name: "中国", postalPrefix: ["7"] },
    { id: "shikoku", name: "四国", postalPrefix: ["7","8"] },
    { id: "kyushu", name: "九州・沖縄", postalPrefix: ["8","9"] },
  ],

  // ─── 月ごとの季節マッピング ───
  monthSeason: {
    1: "winter", 2: "winter", 3: "spring", 4: "spring",
    5: "spring", 6: "summer", 7: "summer", 8: "summer",
    9: "autumn", 10: "autumn", 11: "autumn", 12: "winter"
  },

  seasonNames: {
    spring: { jp: "春", en: "Spring", months: "3月〜5月", color: "#5cb85c" },
    summer: { jp: "夏", en: "Summer", months: "6月〜8月", color: "#e85d30" },
    autumn: { jp: "秋", en: "Autumn", months: "9月〜11月", color: "#b8860b" },
    winter: { jp: "冬", en: "Winter", months: "12月〜2月", color: "#6a1bb2" },
  },

  // ─── 旬の野菜データ ───
  vegetables: [
    // ── 春 ──
    {
      id: "takenoko",
      name: "たけのこ",
      nameEn: "Bamboo Shoot",
      season: "spring",
      months: [3, 4, 5],
      emoji: "🎋",
      nutrition: "食物繊維が豊富で、カリウム、ビタミンB群を含みます。低カロリーでダイエットにも最適。",
      tips: "切り口が白く、穂先が黄色いものが新鮮。小ぶりで重みのあるものを選びましょう。",
      storage: "茹でてから水に浸し、冷蔵庫で保存。水は毎日取り替えて3〜4日以内に使い切りましょう。",
      facts: "旬の時期は栄養価が最も高く、えぐみも少ない。掘りたてほど美味しい。",
      regions: ["kanto", "kinki", "kyushu", "chugoku"],
    },
    {
      id: "cabbage",
      name: "新キャベツ",
      nameEn: "Spring Cabbage",
      season: "spring",
      months: [3, 4, 5],
      emoji: "🥬",
      nutrition: "ビタミンCが豊富で、胃の粘膜を保護するビタミンU（キャベジン）を含みます。",
      tips: "葉が柔らかく巻きがゆるいものが春キャベツの特徴。ずっしり重いものを選んで。",
      storage: "芯をくり抜き、湿らせたキッチンペーパーを詰めてポリ袋に入れ冷蔵庫へ。",
      facts: "通常のキャベツに比べて水分が多く柔らかいため、生食サラダに最適です。",
      regions: ["kanto", "chubu", "kinki", "chugoku", "kyushu"],
    },
    {
      id: "asparagus",
      name: "アスパラガス",
      nameEn: "Asparagus",
      season: "spring",
      months: [4, 5, 6],
      emoji: "🌿",
      nutrition: "アスパラギン酸が疲労回復に効果的。葉酸、ビタミンK、ルチンも豊富。",
      tips: "穂先がしまっていて、茎が太く真っすぐなものが良品。切り口がみずみずしいものを。",
      storage: "濡れた新聞紙で包み、穂先を上にして立てて冷蔵庫の野菜室へ。2〜3日で使い切って。",
      facts: "北海道産が有名ですが、佐賀県や長野県も主要産地。グリーンとホワイトがあります。",
      regions: ["hokkaido", "tohoku", "kanto", "chubu"],
    },
    {
      id: "nanohana",
      name: "菜の花",
      nameEn: "Rapeseed Blossoms",
      season: "spring",
      months: [2, 3, 4],
      emoji: "🌼",
      nutrition: "β-カロテン、ビタミンC、鉄分が非常に豊富。ほうれん草以上の栄養価を誇ります。",
      tips: "蕾がしっかり閉じていて、茎にハリがあるものが新鮮。花が咲いていると苦味が強い。",
      storage: "湿らせた新聞紙で包みポリ袋に入れ冷蔵庫へ。できるだけ早く使い切りましょう。",
      facts: "春を告げる野菜の代表格。ほろ苦さが大人の味わいで、おひたしや天ぷらに最適。",
      regions: ["kanto", "kinki", "chugoku", "shikoku", "kyushu"],
    },
    {
      id: "shin_tamanegi",
      name: "新たまねぎ",
      nameEn: "New Onion",
      season: "spring",
      months: [3, 4, 5],
      emoji: "🧅",
      nutrition: "硫化アリルが血液をサラサラにし、ビタミンB1の吸収を助けます。ケルセチンも豊富。",
      tips: "表面にツヤがあり、押してみて硬いものを選びましょう。芽が出ていないものが良品。",
      storage: "通常のたまねぎと違い水分が多いので、冷蔵庫の野菜室で保存。1週間を目安に。",
      facts: "水にさらす時間は短めに。辛みが少ないのでスライスして生食が美味しい。",
      regions: ["kanto", "kinki", "shikoku", "kyushu"],
    },

    // ── 夏 ──
    {
      id: "tomato",
      name: "トマト",
      nameEn: "Tomato",
      season: "summer",
      months: [6, 7, 8],
      emoji: "🍅",
      nutrition: "リコピンが豊富で抗酸化作用が高い。旬の時期はβ-カロテン含有量が約2倍に。ビタミンCも豊富。",
      tips: "ヘタが緑色でピンとしていて、全体が均一に赤いものを。ずっしり重いものが糖度が高い。",
      storage: "常温で追熟させてから冷蔵庫へ。冷凍保存も可能で、凍ったまま料理に使えます。",
      facts: "旬のトマトは冬のハウス栽培と比べてリコピンが約3倍。太陽の恵みが詰まっています。",
      regions: ["hokkaido", "tohoku", "kanto", "chubu", "kinki", "kyushu"],
    },
    {
      id: "cucumber",
      name: "きゅうり",
      nameEn: "Cucumber",
      season: "summer",
      months: [6, 7, 8],
      emoji: "🥒",
      nutrition: "カリウムが豊富でむくみ解消に。水分が約95%で夏の水分補給にも。ビタミンKも含有。",
      tips: "イボがしっかりしていてチクチクするものが新鮮。太さが均一で色が濃いものを選んで。",
      storage: "水分を拭き取り、ラップで包んで冷蔵庫の野菜室へ。ヘタを上にして立てて保存。",
      facts: "世界で最もカロリーの低い野菜としてギネスに登録。体を冷やす効果があり夏にぴったり。",
      regions: ["kanto", "chubu", "tohoku", "kyushu"],
    },
    {
      id: "nasu",
      name: "なす",
      nameEn: "Eggplant",
      season: "summer",
      months: [6, 7, 8, 9],
      emoji: "🍆",
      nutrition: "ナスニンというポリフェノールが豊富で抗酸化作用が高い。カリウム、食物繊維も含有。",
      tips: "ヘタのトゲがしっかりしていて痛いくらいのものが新鮮。皮にツヤとハリがあるものを。",
      storage: "1本ずつラップで包み、冷蔵庫の野菜室へ。5℃以下は低温障害を起こすので注意。",
      facts: "「秋なすは嫁に食わすな」は、美味しすぎるからという説も。焼き・揚げ・煮、何でも合います。",
      regions: ["kanto", "kinki", "chubu", "kyushu", "chugoku"],
    },
    {
      id: "corn",
      name: "とうもろこし",
      nameEn: "Corn",
      season: "summer",
      months: [6, 7, 8],
      emoji: "🌽",
      nutrition: "糖質、ビタミンB1、B2、食物繊維が豊富。エネルギー補給に最適な夏野菜。",
      tips: "ヒゲが褐色で多いものが実が充実。皮が鮮やかな緑色で、粒にツヤがあるものを。",
      storage: "収穫後は糖度がどんどん落ちるので、すぐに茹でるのがベスト。茹でてから冷蔵・冷凍保存。",
      facts: "朝採りが最も甘い。茹でる時は水から入れて沸騰後3〜5分がベスト。",
      regions: ["hokkaido", "tohoku", "kanto", "chubu"],
    },
    {
      id: "edamame",
      name: "枝豆",
      nameEn: "Edamame",
      season: "summer",
      months: [6, 7, 8],
      emoji: "🫛",
      nutrition: "良質なタンパク質、ビタミンB1、葉酸、鉄分が豊富。メチオニンがアルコール分解を助けます。",
      tips: "さやの色が鮮やかな緑で、産毛がしっかり付いているものを。粒が大きく膨らんでいるものが◎。",
      storage: "購入後すぐに茹でるのがベスト。茹でた後は冷凍保存で約1ヶ月持ちます。",
      facts: "大豆の未熟な状態が枝豆。ビールのお供は理にかなっていて、メチオニンが肝機能を助けます。",
      regions: ["tohoku", "kanto", "chubu", "hokkaido"],
    },

    // ── 秋 ──
    {
      id: "satsumaimo",
      name: "さつまいも",
      nameEn: "Sweet Potato",
      season: "autumn",
      months: [9, 10, 11],
      emoji: "🍠",
      nutrition: "ビタミンC、食物繊維、カリウムが豊富。加熱してもビタミンCが壊れにくいのが特徴。",
      tips: "表面にツヤがあり、ひげ根の跡が少なく均一な形のものを。ずっしり重いものが良品。",
      storage: "新聞紙で包み、常温の冷暗所で保存。冷蔵庫は低温障害を起こすのでNG。",
      facts: "収穫後1〜2ヶ月寝かせると、デンプンが糖に変わり甘みが増します。",
      regions: ["kanto", "kyushu", "shikoku", "chubu"],
    },
    {
      id: "kabocha",
      name: "かぼちゃ",
      nameEn: "Japanese Pumpkin",
      season: "autumn",
      months: [9, 10, 11],
      emoji: "🎃",
      nutrition: "β-カロテンが非常に豊富で、ビタミンE、ビタミンCも。免疫力向上に効果的。",
      tips: "ヘタが乾燥してコルク状になっているものが完熟。ずっしり重く、皮が硬いものを。",
      storage: "丸ごとなら常温で2〜3ヶ月保存可能。カットしたら種とワタを除き、ラップで冷蔵庫へ。",
      facts: "冬至にかぼちゃを食べる風習は、栄養豊富で風邪予防になることから。保存性も高い。",
      regions: ["hokkaido", "kanto", "chubu", "kinki", "kyushu"],
    },
    {
      id: "kinoko",
      name: "きのこ類",
      nameEn: "Mushrooms",
      season: "autumn",
      months: [9, 10, 11],
      emoji: "🍄",
      nutrition: "ビタミンD、食物繊維、ビタミンB群が豊富。低カロリーでダイエットにも最適。",
      tips: "しいたけは肉厚で傘が開ききっていないもの。まいたけは色が濃く、パリッとしたものを。",
      storage: "水洗いはNG。キッチンペーパーで包み、ポリ袋に入れて冷蔵庫の野菜室へ。冷凍で旨味UP。",
      facts: "冷凍すると細胞が壊れて旨味成分が出やすくなります。調理時は凍ったまま使って。",
      regions: ["hokkaido", "tohoku", "kanto", "chubu", "kinki"],
    },
    {
      id: "renkon",
      name: "れんこん",
      nameEn: "Lotus Root",
      season: "autumn",
      months: [10, 11, 12],
      emoji: "🪷",
      nutrition: "ビタミンC、食物繊維、ポリフェノール（タンニン）が豊富。胃腸の調子を整える効果も。",
      tips: "切り口が白く、穴が小さく均一なものを。ずっしり重みがあり、節と節の間が長いものが◎。",
      storage: "切り口をラップで包み、ポリ袋に入れて冷蔵庫へ。酢水に浸けると変色を防げます。",
      facts: "穴が空いているので「先が見通せる」縁起物として、おせち料理に欠かせない食材。",
      regions: ["kanto", "chubu", "kinki", "chugoku", "kyushu"],
    },
    {
      id: "satoimo",
      name: "里芋",
      nameEn: "Taro",
      season: "autumn",
      months: [9, 10, 11],
      emoji: "🥔",
      nutrition: "カリウム、食物繊維が豊富。ぬめり成分のガラクタンが免疫力を高める効果。",
      tips: "表面の縞模様がはっきりしていて、ふっくら丸いものを。泥付きの方が鮮度が長持ち。",
      storage: "泥付きのまま新聞紙で包み、冷暗所で保存。洗ったものは冷蔵庫で3〜4日以内に。",
      facts: "日本人と里芋の付き合いは稲作よりも古く、縄文時代から栽培されていたとも。",
      regions: ["tohoku", "kanto", "chubu", "kinki", "chugoku"],
    },

    // ── 冬 ──
    {
      id: "daikon",
      name: "大根",
      nameEn: "Daikon Radish",
      season: "winter",
      months: [11, 12, 1, 2],
      emoji: "🥕",
      nutrition: "消化酵素ジアスターゼが胃腸の働きを助ける。ビタミンC、カリウムも豊富。葉にはβ-カロテンも。",
      tips: "ずっしり重く、表面にハリとツヤがあるものを。ヒゲ根が少なく真っすぐなものが良品。",
      storage: "葉を切り落とし、新聞紙で包んで冷蔵庫へ。大きい場合はカットしてラップで保存。",
      facts: "上部は甘みが強くサラダに、中央は煮物に、下部は辛みが強く大根おろしに最適。",
      regions: ["hokkaido", "tohoku", "kanto", "chubu", "kinki", "kyushu"],
    },
    {
      id: "hakusai",
      name: "白菜",
      nameEn: "Napa Cabbage",
      season: "winter",
      months: [11, 12, 1, 2],
      emoji: "🥬",
      nutrition: "ビタミンC、カリウム、食物繊維が豊富。水分が約95%で低カロリー。鍋料理に最適。",
      tips: "葉が白くて厚みがあり、持つとずっしり重いものを。外葉がしっかり巻いているものが◎。",
      storage: "丸ごとなら新聞紙で包み冷暗所で2〜3週間。カットしたものはラップで冷蔵庫へ。",
      facts: "霜に当たると甘みが増す。鍋料理で使うとビタミンCがスープに溶け出し、余さず摂取できます。",
      regions: ["hokkaido", "tohoku", "kanto", "chubu", "kinki", "chugoku"],
    },
    {
      id: "hourensou",
      name: "ほうれん草",
      nameEn: "Spinach",
      season: "winter",
      months: [11, 12, 1, 2],
      emoji: "🥬",
      nutrition: "鉄分、葉酸、β-カロテン、ビタミンCが豊富。冬採りは夏採りの約3倍のビタミンCを含有。",
      tips: "葉が肉厚で濃い緑色のものを。根元がピンク色のものは甘みが強い良品。",
      storage: "湿らせた新聞紙で包み、根を下にして立てて冷蔵庫へ。3日以内に使い切るのがベスト。",
      facts: "旬の冬のほうれん草は栄養価が格段に高い。茹で時間は30秒〜1分で十分です。",
      regions: ["kanto", "chubu", "kinki", "tohoku", "chugoku"],
    },
    {
      id: "broccoli",
      name: "ブロッコリー",
      nameEn: "Broccoli",
      season: "winter",
      months: [11, 12, 1, 2, 3],
      emoji: "🥦",
      nutrition: "ビタミンC含有量はレモン以上。β-カロテン、ビタミンK、葉酸、スルフォラファンも豊富。",
      tips: "蕾が小さく密集して紫がかっているものが栄養価が高い。茎も栄養豊富なので食べて。",
      storage: "ポリ袋に入れ冷蔵庫の野菜室へ。小房に分けて茹でてから冷凍保存も可能。",
      facts: "2026年から「指定野菜」に昇格。茎には蕾以上のビタミンCが含まれています。",
      regions: ["hokkaido", "kanto", "chubu", "kinki", "kyushu"],
    },
    {
      id: "negi",
      name: "長ねぎ",
      nameEn: "Japanese Leek",
      season: "winter",
      months: [11, 12, 1, 2],
      emoji: "🧅",
      nutrition: "硫化アリルが血行促進・殺菌効果。ビタミンC、葉酸も含有。風邪予防に効果的。",
      tips: "白い部分が長く、弾力があるものを。緑と白の境界がはっきりしているものが良品。",
      storage: "新聞紙で包み冷暗所へ。カットしたものはラップで冷蔵庫へ。小口切りで冷凍も◎。",
      facts: "関東では白い部分、関西では青い部分を好んで食べる文化の違いがあります。",
      regions: ["kanto", "tohoku", "chubu", "hokkaido"],
    },
  ],

  // ─── レシピデータ ───
  recipes: [
    // ── 春レシピ ──
    {
      id: "takenoko_gohan",
      title: "たけのこご飯",
      subtitle: "春の定番炊き込みご飯",
      season: "spring",
      time: 60,
      servings: 4,
      difficulty: "ふつう",
      mainVegetable: "takenoko",
      calories: 320,
      image: "spring",
      ingredients: [
        { name: "米", amount: "2合" },
        { name: "たけのこ（茹で）", amount: "200g" },
        { name: "油揚げ", amount: "1枚" },
        { name: "だし汁", amount: "適量" },
        { name: "醤油", amount: "大さじ2" },
        { name: "みりん", amount: "大さじ1" },
        { name: "酒", amount: "大さじ1" },
        { name: "塩", amount: "小さじ1/2" },
        { name: "木の芽", amount: "適量" },
      ],
      steps: [
        "米は研いで30分ほど浸水させ、ザルに上げておく。",
        "たけのこは穂先は薄切り、根元は1cm角に切る。油揚げは油抜きして細切りに。",
        "炊飯器に米を入れ、醤油、みりん、酒、塩を加え、だし汁を2合の目盛りまで注ぐ。",
        "たけのこと油揚げを上にのせ（混ぜない）、通常モードで炊飯する。",
        "炊き上がったらさっくりと混ぜ、器に盛り、木の芽を添えて完成。",
      ],
      tips: "たけのこは食感を楽しむために、穂先と根元で切り方を変えるのがポイントです。",
    },
    {
      id: "nanohana_ohitashi",
      title: "菜の花のおひたし",
      subtitle: "ほろ苦さが春を告げる一品",
      season: "spring",
      time: 15,
      servings: 2,
      difficulty: "かんたん",
      mainVegetable: "nanohana",
      calories: 45,
      image: "spring",
      ingredients: [
        { name: "菜の花", amount: "1束（約200g）" },
        { name: "だし汁", amount: "100ml" },
        { name: "薄口醤油", amount: "大さじ1" },
        { name: "みりん", amount: "小さじ1" },
        { name: "かつお節", amount: "適量" },
        { name: "からし", amount: "お好みで" },
      ],
      steps: [
        "菜の花は根元の硬い部分を切り落とし、よく洗う。",
        "沸騰した湯に塩少々を入れ、茎の部分から先に入れ30秒、穂先を入れてさらに30秒茹でる。",
        "すぐに冷水に取り、色止めをする。水気をしっかり絞り、3〜4cm長さに切る。",
        "だし汁、薄口醤油、みりんを合わせた浸し汁に漬け、冷蔵庫で30分ほど味をなじませる。",
        "器に盛り、かつお節をのせ、お好みでからしを添えて完成。",
      ],
      tips: "茹ですぎると色も食感も悪くなります。さっと茹でてすぐ冷水に取るのがコツ。",
    },
    {
      id: "spring_cabbage_coleslaw",
      title: "春キャベツのコールスロー",
      subtitle: "柔らかな甘みを活かした生サラダ",
      season: "spring",
      time: 15,
      servings: 4,
      difficulty: "かんたん",
      mainVegetable: "cabbage",
      calories: 120,
      image: "spring",
      ingredients: [
        { name: "春キャベツ", amount: "1/4個" },
        { name: "にんじん", amount: "1/3本" },
        { name: "コーン", amount: "大さじ3" },
        { name: "マヨネーズ", amount: "大さじ3" },
        { name: "酢", amount: "大さじ1" },
        { name: "砂糖", amount: "小さじ1" },
        { name: "塩・こしょう", amount: "少々" },
      ],
      steps: [
        "春キャベツは千切りにし、塩小さじ1/2を振って5分置き、水気を絞る。",
        "にんじんは千切りにする。",
        "ボウルにマヨネーズ、酢、砂糖、塩・こしょうを混ぜ合わせる。",
        "キャベツ、にんじん、コーンを加えてよく和える。",
        "冷蔵庫で30分ほど冷やすと味がなじんで美味しくなります。",
      ],
      tips: "春キャベツは柔らかいので、水気をしっかり絞ると水っぽくなりません。",
    },
    {
      id: "asparagus_nikumaki",
      title: "アスパラガスの肉巻き",
      subtitle: "お弁当にも最適な定番おかず",
      season: "spring",
      time: 20,
      servings: 2,
      difficulty: "ふつう",
      mainVegetable: "asparagus",
      calories: 280,
      image: "spring",
      ingredients: [
        { name: "アスパラガス", amount: "6本" },
        { name: "豚バラ薄切り肉", amount: "6枚" },
        { name: "醤油", amount: "大さじ1.5" },
        { name: "みりん", amount: "大さじ1" },
        { name: "酒", amount: "大さじ1" },
        { name: "砂糖", amount: "小さじ1" },
        { name: "塩・こしょう", amount: "少々" },
        { name: "サラダ油", amount: "小さじ1" },
      ],
      steps: [
        "アスパラガスは根元の硬い部分を切り落とし、下半分の皮をピーラーでむく。",
        "豚肉を広げて塩・こしょうを振り、アスパラガスに斜めにきつく巻きつける。",
        "フライパンにサラダ油を中火で熱し、巻き終わりを下にして焼く。",
        "全体に焼き色がついたら、醤油、みりん、酒、砂糖を加え、転がしながら絡める。",
        "タレにとろみがついたら完成。斜め半分に切って盛り付ける。",
      ],
      tips: "肉をきつめに巻くと、焼いている時にほどけにくくなります。",
    },

    // ── 夏レシピ ──
    {
      id: "nasu_miso",
      title: "なすの味噌炒め",
      subtitle: "ご飯がすすむ夏の定番おかず",
      season: "summer",
      time: 15,
      servings: 2,
      difficulty: "かんたん",
      mainVegetable: "nasu",
      calories: 180,
      image: "summer",
      ingredients: [
        { name: "なす", amount: "3本" },
        { name: "ピーマン", amount: "2個" },
        { name: "豚こま肉", amount: "100g" },
        { name: "味噌", amount: "大さじ2" },
        { name: "砂糖", amount: "大さじ1" },
        { name: "酒", amount: "大さじ1" },
        { name: "みりん", amount: "大さじ1" },
        { name: "ごま油", amount: "大さじ1" },
        { name: "生姜（すりおろし）", amount: "小さじ1" },
      ],
      steps: [
        "なすは乱切りにし、水に5分さらしてアク抜き。ピーマンは一口大に切る。",
        "味噌、砂糖、酒、みりん、生姜を混ぜ合わせておく（合わせ調味料）。",
        "フライパンにごま油を中火で熱し、豚肉を炒める。色が変わったらなすを加え炒める。",
        "なすがしんなりしたらピーマンを加え、合わせ調味料を回し入れる。",
        "全体に調味料が絡んだら完成。お好みで白ごまを振る。",
      ],
      tips: "なすは油を吸いやすいので、先に電子レンジで1分加熱すると油の吸収を抑えられます。",
    },
    {
      id: "tomato_cold_pasta",
      title: "トマトの冷製パスタ",
      subtitle: "暑い日にぴったりの冷たいパスタ",
      season: "summer",
      time: 25,
      servings: 2,
      difficulty: "かんたん",
      mainVegetable: "tomato",
      calories: 380,
      image: "summer",
      ingredients: [
        { name: "カッペリーニ（細めのパスタ）", amount: "160g" },
        { name: "トマト", amount: "3個" },
        { name: "バジル", amount: "6枚" },
        { name: "にんにく", amount: "1片" },
        { name: "オリーブオイル", amount: "大さじ3" },
        { name: "塩", amount: "小さじ1" },
        { name: "黒こしょう", amount: "少々" },
        { name: "レモン汁", amount: "小さじ1" },
      ],
      steps: [
        "トマトは湯むきして種を除き、1cm角に切る。にんにくはみじん切りに。",
        "ボウルにトマト、にんにく、オリーブオイル、塩、レモン汁を合わせ、冷蔵庫で冷やす。",
        "パスタを表示時間通りに茹で、氷水でしっかり冷やし、水気を切る。",
        "冷やしたトマトソースとパスタを和える。",
        "器に盛り、バジルをちぎってのせ、黒こしょうを振って完成。",
      ],
      tips: "旬のトマトの甘みとリコピンを丸ごと楽しめます。ソースは前日に作って冷やすとより美味しい。",
    },
    {
      id: "cucumber_sunomono",
      title: "きゅうりとわかめの酢の物",
      subtitle: "さっぱり箸休めの定番",
      season: "summer",
      time: 10,
      servings: 2,
      difficulty: "かんたん",
      mainVegetable: "cucumber",
      calories: 35,
      image: "summer",
      ingredients: [
        { name: "きゅうり", amount: "2本" },
        { name: "乾燥わかめ", amount: "大さじ1" },
        { name: "しらす", amount: "大さじ2" },
        { name: "酢", amount: "大さじ2" },
        { name: "砂糖", amount: "大さじ1" },
        { name: "薄口醤油", amount: "小さじ1" },
        { name: "塩", amount: "少々" },
        { name: "白ごま", amount: "適量" },
      ],
      steps: [
        "きゅうりは薄い小口切りにし、塩を振って5分おき、水気をしっかり絞る。",
        "乾燥わかめは水で戻し、水気を切る。",
        "酢、砂糖、薄口醤油を混ぜ合わせて三杯酢を作る。",
        "きゅうり、わかめ、しらすを三杯酢で和える。",
        "器に盛り、白ごまを振って完成。",
      ],
      tips: "きゅうりの水気をしっかり絞ると、味がぼやけず美味しく仕上がります。",
    },
    {
      id: "corn_rice",
      title: "とうもろこしご飯",
      subtitle: "甘い夏の恵みを炊き込みで",
      season: "summer",
      time: 50,
      servings: 4,
      difficulty: "かんたん",
      mainVegetable: "corn",
      calories: 310,
      image: "summer",
      ingredients: [
        { name: "米", amount: "2合" },
        { name: "とうもろこし", amount: "1本" },
        { name: "酒", amount: "大さじ1" },
        { name: "塩", amount: "小さじ1" },
        { name: "バター", amount: "10g" },
        { name: "醤油", amount: "小さじ1（仕上げ用）" },
      ],
      steps: [
        "米は研いで30分浸水させ、ザルに上げる。",
        "とうもろこしは実を包丁でそぎ落とす。芯も取っておく。",
        "炊飯器に米、酒、塩を入れ、2合の目盛りまで水を注ぐ。",
        "とうもろこしの実を上にのせ、芯も一緒に入れて炊飯する（芯から出汁が出る）。",
        "炊き上がったら芯を取り除き、バターと醤油を加えてさっくり混ぜて完成。",
      ],
      tips: "芯も一緒に炊くのがポイント！とうもろこしの旨味が染み出して格段に美味しくなります。",
    },

    // ── 秋レシピ ──
    {
      id: "kabocha_nimono",
      title: "かぼちゃの煮物",
      subtitle: "ほっくり甘い日本の家庭の味",
      season: "autumn",
      time: 30,
      servings: 4,
      difficulty: "かんたん",
      mainVegetable: "kabocha",
      calories: 140,
      image: "autumn",
      ingredients: [
        { name: "かぼちゃ", amount: "1/4個（約400g）" },
        { name: "だし汁", amount: "200ml" },
        { name: "醤油", amount: "大さじ1.5" },
        { name: "みりん", amount: "大さじ2" },
        { name: "砂糖", amount: "大さじ1" },
        { name: "酒", amount: "大さじ1" },
      ],
      steps: [
        "かぼちゃは種とワタを取り、一口大に切る。皮は所々むく（面取り）。",
        "鍋にだし汁、醤油、みりん、砂糖、酒を入れて中火にかける。",
        "煮立ったらかぼちゃを皮を下にして並べ入れる。",
        "落とし蓋をして弱火で15〜20分、竹串がスッと通るまで煮る。",
        "火を止めてそのまま10分置き、味を含ませたら完成。",
      ],
      tips: "皮を下にして煮ると煮崩れ防止に。面取りすると味が染みやすくなります。",
    },
    {
      id: "kinoko_takikomi",
      title: "きのこの炊き込みご飯",
      subtitle: "秋の香りたっぷりの贅沢ご飯",
      season: "autumn",
      time: 60,
      servings: 4,
      difficulty: "ふつう",
      mainVegetable: "kinoko",
      calories: 290,
      image: "autumn",
      ingredients: [
        { name: "米", amount: "2合" },
        { name: "しめじ", amount: "1パック" },
        { name: "まいたけ", amount: "1パック" },
        { name: "しいたけ", amount: "4枚" },
        { name: "油揚げ", amount: "1枚" },
        { name: "だし汁", amount: "適量" },
        { name: "醤油", amount: "大さじ2" },
        { name: "酒", amount: "大さじ2" },
        { name: "みりん", amount: "大さじ1" },
        { name: "塩", amount: "小さじ1/2" },
        { name: "三つ葉", amount: "適量" },
      ],
      steps: [
        "米は研いで30分浸水させ、ザルに上げる。",
        "しめじとまいたけは石づきを取ってほぐす。しいたけは薄切り。油揚げは細切りに。",
        "炊飯器に米、醤油、酒、みりん、塩を入れ、だし汁を2合の目盛りまで注ぐ。",
        "きのこ類と油揚げをのせ（混ぜない）、通常モードで炊飯。",
        "炊き上がったらさっくり混ぜ、器に盛って三つ葉を添えて完成。",
      ],
      tips: "きのこは3種類以上混ぜると旨味の相乗効果で格段に美味しくなります。",
    },
    {
      id: "renkon_kinpira",
      title: "れんこんのきんぴら",
      subtitle: "シャキシャキ食感がたまらない",
      season: "autumn",
      time: 15,
      servings: 2,
      difficulty: "かんたん",
      mainVegetable: "renkon",
      calories: 110,
      image: "autumn",
      ingredients: [
        { name: "れんこん", amount: "200g" },
        { name: "にんじん", amount: "1/3本" },
        { name: "醤油", amount: "大さじ1.5" },
        { name: "みりん", amount: "大さじ1" },
        { name: "砂糖", amount: "小さじ1" },
        { name: "鷹の爪（輪切り）", amount: "少々" },
        { name: "ごま油", amount: "大さじ1" },
        { name: "白ごま", amount: "適量" },
      ],
      steps: [
        "れんこんは薄い半月切りにし、酢水に5分さらす。にんじんは細切りに。",
        "フライパンにごま油と鷹の爪を入れ中火にかける。",
        "水気を切ったれんこんとにんじんを加え、2〜3分炒める。",
        "醤油、みりん、砂糖を加え、汁気がなくなるまで炒め合わせる。",
        "器に盛り、白ごまを振って完成。",
      ],
      tips: "れんこんの食感を残すために、炒めすぎないのがポイント。お弁当にも◎。",
    },
    {
      id: "satsumaimo_tempura",
      title: "さつまいもの天ぷら",
      subtitle: "サクッとほくほく、秋のごちそう",
      season: "autumn",
      time: 25,
      servings: 2,
      difficulty: "ふつう",
      mainVegetable: "satsumaimo",
      calories: 320,
      image: "autumn",
      ingredients: [
        { name: "さつまいも", amount: "1本（約250g）" },
        { name: "薄力粉", amount: "1/2カップ" },
        { name: "片栗粉", amount: "大さじ1" },
        { name: "冷水", amount: "80ml" },
        { name: "卵", amount: "1個" },
        { name: "揚げ油", amount: "適量" },
        { name: "塩", amount: "適量" },
        { name: "抹茶塩", amount: "お好みで" },
      ],
      steps: [
        "さつまいもは皮付きのまま7〜8mm厚さの斜め切りにし、水に10分さらす。",
        "水気をしっかり拭き取る。",
        "ボウルに卵と冷水を混ぜ、薄力粉と片栗粉を加えてさっくり混ぜる（混ぜすぎない）。",
        "170℃の油でさつまいもに衣をつけて揚げる。低温でじっくり3〜4分。",
        "油を切って盛り付け、塩や抹茶塩を添えて完成。",
      ],
      tips: "低温でじっくり揚げるとさつまいもの甘みが引き出されます。衣は混ぜすぎないこと。",
    },

    // ── 冬レシピ ──
    {
      id: "hakusai_nabe",
      title: "白菜と豚肉のミルフィーユ鍋",
      subtitle: "シンプルなのに絶品の冬の主役",
      season: "winter",
      time: 30,
      servings: 2,
      difficulty: "かんたん",
      mainVegetable: "hakusai",
      calories: 350,
      image: "winter",
      ingredients: [
        { name: "白菜", amount: "1/4株" },
        { name: "豚バラ薄切り肉", amount: "200g" },
        { name: "だし汁", amount: "400ml" },
        { name: "酒", amount: "大さじ2" },
        { name: "塩", amount: "小さじ1" },
        { name: "ポン酢", amount: "適量" },
        { name: "柚子こしょう", amount: "お好みで" },
        { name: "小ねぎ（小口切り）", amount: "適量" },
      ],
      steps: [
        "白菜の葉と豚肉を交互に5〜6枚重ねる。これを3セット作る。",
        "5cm幅に切り、鍋の中に断面を上にしてぎっしり並べる。",
        "だし汁と酒を注ぎ入れ、塩を加える。",
        "蓋をして中火にかけ、煮立ったら弱火で15〜20分煮る。",
        "白菜が柔らかくなったら小ねぎを散らし、ポン酢と柚子こしょうでいただく。",
      ],
      tips: "白菜と豚肉を交互に重ねてカットするだけ。見た目も美しく、おもてなしにも。",
    },
    {
      id: "daikon_nimono",
      title: "ぶり大根",
      subtitle: "冬の旬食材の最強コンビ",
      season: "winter",
      time: 50,
      servings: 4,
      difficulty: "ふつう",
      mainVegetable: "daikon",
      calories: 280,
      image: "winter",
      ingredients: [
        { name: "大根", amount: "1/2本" },
        { name: "ぶり（切り身）", amount: "4切れ" },
        { name: "生姜", amount: "1片" },
        { name: "水", amount: "400ml" },
        { name: "醤油", amount: "大さじ3" },
        { name: "みりん", amount: "大さじ3" },
        { name: "酒", amount: "大さじ3" },
        { name: "砂糖", amount: "大さじ2" },
      ],
      steps: [
        "大根は2cm厚さの半月切りにし、面取りして下茹でする（竹串が通るまで約10分）。",
        "ぶりは熱湯にさっとくぐらせて霜降りにし、冷水で汚れを洗う。",
        "鍋に水、酒、砂糖、みりん、薄切り生姜を入れて煮立てる。",
        "ぶりと大根を入れ、落とし蓋をして弱火で25〜30分煮る。",
        "醤油を加え、さらに10分煮て味を含ませたら完成。",
      ],
      tips: "大根は下茹ですると味が染みやすくなり、ぶりは霜降りすると臭みが取れます。",
    },
    {
      id: "hourensou_gomaae",
      title: "ほうれん草のごま和え",
      subtitle: "栄養満点の定番副菜",
      season: "winter",
      time: 10,
      servings: 2,
      difficulty: "かんたん",
      mainVegetable: "hourensou",
      calories: 65,
      image: "winter",
      ingredients: [
        { name: "ほうれん草", amount: "1束（約200g）" },
        { name: "白すりごま", amount: "大さじ3" },
        { name: "砂糖", amount: "大さじ1" },
        { name: "醤油", amount: "大さじ1.5" },
        { name: "だし汁", amount: "小さじ1" },
      ],
      steps: [
        "ほうれん草は根元に十字の切り込みを入れ、よく洗う。",
        "沸騰した湯に塩を入れ、根元から先に入れて30秒、全体を沈めてさらに30秒茹でる。",
        "すぐに冷水に取り、水気をしっかり絞って3〜4cm長さに切る。",
        "ボウルにすりごま、砂糖、醤油、だし汁を混ぜ合わせ、ごま和えの衣を作る。",
        "ほうれん草を加えて和え、器に盛って完成。",
      ],
      tips: "旬の冬のほうれん草はビタミンCが夏の3倍。根元のピンク色の部分も甘くて美味しいですよ。",
    },
    {
      id: "broccoli_gratin",
      title: "ブロッコリーのグラタン",
      subtitle: "あつあつクリーミーな冬のごちそう",
      season: "winter",
      time: 35,
      servings: 2,
      difficulty: "ふつう",
      mainVegetable: "broccoli",
      calories: 420,
      image: "winter",
      ingredients: [
        { name: "ブロッコリー", amount: "1株" },
        { name: "鶏もも肉", amount: "150g" },
        { name: "たまねぎ", amount: "1/2個" },
        { name: "バター", amount: "20g" },
        { name: "薄力粉", amount: "大さじ2" },
        { name: "牛乳", amount: "300ml" },
        { name: "ピザ用チーズ", amount: "60g" },
        { name: "塩・こしょう", amount: "少々" },
        { name: "コンソメ", amount: "小さじ1" },
      ],
      steps: [
        "ブロッコリーは小房に分け、茎も皮をむいて薄切りに。塩茹でして水気を切る。",
        "鶏肉は一口大、たまねぎは薄切りにする。",
        "フライパンにバターを溶かし、鶏肉とたまねぎを炒める。薄力粉を振り入れ粉っぽさがなくなるまで炒める。",
        "牛乳を少しずつ加えながら混ぜ、とろみがついたら塩・こしょう、コンソメで味を調える。",
        "耐熱皿にブロッコリーとホワイトソースを入れ、チーズをのせて230℃のオーブンで10〜12分焼いて完成。",
      ],
      tips: "ブロッコリーの茎も使うことで食感のアクセントに。茎にはつぼみ以上のビタミンCが含まれます。",
    },
  ],
};
